apiVersion: v1
kind: Pod
metadata:
  name: pause-resume-future-pt
  namespace: default  
spec:
  nodeSelector:
    type: data
  restartPolicy: Never
  hostNetwork: true
  containers:
  - name: pause-future-pt
    securityContext:
      privileged: true
    image: registry.ricequant.com:5000/pause-resume:0.1.8
    imagePullPolicy: IfNotPresent
    env:
    - name: PYTHONPATH
      value: /tmp
    - name: TZ
      value: Asia/Shanghai
    volumeMounts:
    - name: log
      mountPath: /logs/
    - name: config
      mountPath: /tmp/
    command: ["/bin/bash"]
    args: ["-c", "pause_resume_tool pause -r pt -s future; pause_resume_tool resume -r pt -s future"]
  volumes:
  - name: log
    hostPath:
      path: /logs
  - name: config
    configMap:
      name: pause-resume-config
      items:
        - key: conf.py
          path: conf.py
            
