apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: update-md-china-instruments
  namespace: default
spec:
  schedule: "30 */4 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 50
  failedJobsHistoryLimit: 50
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            type: web
          restartPolicy: OnFailure
          hostNetwork: true
          containers:
          - name: md-update
            securityContext:
              privileged: true
            image: registry.ricequant.com:5000/rsync-ssh
            env:
            - name: RSYNC_PASSWORD
              value: eZ8SLuOCWJKHI5BStKbfcBrbIbkVGE
            - name: TZ
              value: Asia/Shanghai
            volumeMounts:
            - name: rqstaic
              mountPath: /mnt/rqstatic/
            args:
            - rsync
            - -razP 
            - --port
            - "58888"
            - xyzq@10.233.1.24::historical_data/Instruments/latest/china/china_instruments.txt
            - /mnt/rqstatic/data/
          volumes:
          - name: rqstaic
            hostPath:
              path: /mnt/rqstatic/