apiVersion: v1
kind: Pod
metadata:
  name: update-md-corporate-events-bt2
  namespace: default
  lables: 
    name: update-md-corporate-events-bt2
spec:
  nodeSelector:
    kubernetes.io/hostname: bt2
  restartPolicy: Never
  hostNetwork: true
  containers:
  - name: md-update
    securityContext:
      privileged: true
    image: registry.ricequant.com:5000/rsync-ssh
    imagePullPolicy: Always
    env:
    - name: RSYNC_PASSWORD
      value: eZ8SLuOCWJKHI5BStKbfcBrbIbkVGE
    - name: TZ
      value: Asia/Shanghai
    volumeMounts:
    - name: datapath
      mountPath: /data/
    args:
    - rsync
    - -razP 
    - --port
    - "58888"
    - xyzq@10.233.1.24::historical_data_unadjusted/corporate_events
    - /data/hd/  
  volumes:
  - name: datapath
    hostPath:
      path: /data/

              
